/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaJni_TestJniInterface */

#ifndef _Included_JavaJni_TestJniInterface
#define _Included_JavaJni_TestJniInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaJni_TestJniInterface
 * Method:    JavaCallC
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JavaJni_TestJniInterface_JavaCallC
  (JNIEnv *, jclass, jstring);

/*
 * Class:     JavaJni_TestJniInterface
 * Method:    CCallJava
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JavaJni_TestJniInterface_CCallJava
  (JNIEnv *, jclass);

/*
 * Class:     JavaJni_TestJniInterface
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_JavaJni_TestJniInterface_add
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     JavaJni_TestJniInterface
 * Method:    CGetJavaPrams
 * Signature: (LJavaJni/TestJniInterface;)V
 */
JNIEXPORT void JNICALL Java_JavaJni_TestJniInterface_CGetJavaPrams
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
